# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SoundCamera' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SoundCamera
  pod 'AudioKit', '~> 3.7'
  target 'SoundCameraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SoundCameraUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
